package com.marcow.bible.core.database

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.nio.file.Files
import java.nio.file.Path
import java.sql.Connection
import java.sql.DriverManager
import java.sql.ResultSet

/**
 * Verifies the committed pre-packaged database, the same guarantees `tool/build_bible_db.mjs`
 * asserts when it builds the file.
 *
 * The asset is opened straight off disk with sqlite-jdbc instead of through Room, so this runs in
 * the plain JVM `test` task. CI has no emulator, and the failure this guards against — an asset
 * that silently ships with the wrong book or chapter count — is exactly the kind of thing that
 * must not wait for a device. The column shape is asserted too, because the pre-packaged file is
 * hand-written: if an `@Entity` in this module changes, the Room identity hash goes stale and
 * Room throws on every open, and this test is the cheap early warning.
 */
class PrepackagedBibleDbTest {
    private val asset: Path =
        generateSequence(Path.of(System.getProperty("user.dir")).toAbsolutePath()) { it.parent }
            .map { it.resolve("app/src/main/assets/databases/bible.db") }
            .firstOrNull(Files::exists)
            ?: error("pre-packaged asset not found from ${System.getProperty("user.dir")}")

    /**
     * `DriverManager` rather than `org.sqlite.JDBC.createConnection`, whose only overload wants a
     * `Properties` as its second argument and so has no one-argument form to call. sqlite-jdbc
     * registers itself as a JDBC driver, so the URL opens the same database either way — the same
     * swap `BibleSearchTest` makes for the same reason.
     */
    private fun <T> withDb(block: (Connection) -> T): T =
        DriverManager.getConnection("jdbc:sqlite:$asset").use(block)

    @Test
    fun `ships 66 books in canon order`() = withDb { db ->
        val rows = db.query("SELECT id, ordinal, chapters FROM books ORDER BY ordinal")
        rows.use {
            var expectedOrdinal = 1
            while (it.next()) {
                assertEquals(expectedOrdinal, it.int("ordinal"), "ordinal gap at ${it.text("id")}")
                assertTrue(it.int("chapters") > 0, "${it.text("id")} has no chapters")
                expectedOrdinal++
            }
            assertEquals(66, expectedOrdinal - 1)
        }
    }

    @Test
    fun `ships 1189 chapters and no empty one`() = withDb { db ->
        db.query(
            """
            SELECT COUNT(*) AS total,
                   SUM(CASE WHEN verse_count = 0 THEN 1 ELSE 0 END) AS empty_chapters,
                   SUM(verse_count) AS total_verses
            FROM (
                SELECT book_id, chapter, COUNT(*) AS verse_count
                FROM verses GROUP BY book_id, chapter
            )
            """,
        ).use {
            it.next()
            assertEquals(1189, it.int("total"))
            assertEquals(0, it.int("empty_chapters"))
            // CUV and WEB differ in length in a few chapters, so a row exists per verse index of
            // the longer translation, not per translation.
            assertEquals(31107, it.int("total_verses"))
        }
    }

    @Test
    fun `every verse has text in at least one translation`() = withDb { db ->
        db.query("SELECT COUNT(*) AS n FROM verses WHERE text_cuv IS NULL AND text_web IS NULL").use {
            it.next()
            assertEquals(0, it.int("n"))
        }
    }

    @Test
    fun `declares the schema version Room expects`() = withDb { db ->
        db.query("PRAGMA user_version").use {
            it.next()
            assertEquals(BibleDb.VERSION, it.int(1))
        }
    }

    @Test
    fun `omits room_master_table so Room validates the schema itself`() = withDb { db ->
        // Room's identity hash is generated by KSP from the entity code. A stale hand-written value
        // would make Room throw on every open, so the asset ships without the table and Room fills
        // it in on first launch.
        assertEquals(
            setOf("books", "devotion_cache", "reading_progress", "verses"),
            db.tableNames(),
        )
    }

    @Test
    fun `matches the column shape declared by the entities`() = withDb { db ->
        assertEquals(
            listOf("id", "ordinal", "name_zh", "name_en", "chapters", "testament"),
            db.columns("books").map { it.name },
        )
        assertEquals(
            listOf("book_id", "chapter", "verse", "text_cuv", "text_web"),
            db.columns("verses").map { it.name },
        )
        assertEquals(
            listOf("book_id", "chapter", "verse", "scroll_ratio", "mode", "updated_at"),
            db.columns("reading_progress").map { it.name },
        )
        assertEquals(
            listOf("id", "raw_post", "fetched_at"),
            db.columns("devotion_cache").map { it.name },
        )

        // Nullable in the entity, so nullable on disk too.
        assertEquals(
            listOf("text_cuv", "text_web"),
            db.columns("verses").filterNot { it.notNull }.map { it.name },
        )
        assertEquals(
            listOf("verse"),
            db.columns("reading_progress").filterNot { it.notNull }.map { it.name },
        )
    }

    @Test
    fun `reading_progress is empty so the first launch has no stale position`() = withDb { db ->
        db.query("SELECT COUNT(*) AS n FROM reading_progress").use {
            it.next()
            assertEquals(0, it.int("n"))
        }
    }

    private data class Column(val name: String, val notNull: Boolean)

    private fun Connection.query(sql: String): ResultSet = createStatement().executeQuery(sql)

    private fun Connection.columns(table: String): List<Column> = query("PRAGMA table_info($table)").use { rs ->
        buildList {
            while (rs.next()) {
                add(Column(name = rs.getString("name"), notNull = rs.getInt("notnull") == 1))
            }
        }
    }

    private fun Connection.tableNames(): Set<String> =
        query("SELECT name FROM sqlite_master WHERE type = 'table'").use { rs ->
            buildSet {
                while (rs.next()) add(rs.getString(1))
            }
        }

    private fun ResultSet.int(label: String): Int = getInt(label)

    private fun ResultSet.int(index: Int): Int = getInt(index)

    private fun ResultSet.text(label: String): String = getString(label)
}
